apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-orchestrator
  template:
    metadata:
      labels:
        app: health-orchestrator
    spec:
      containers:
        - name: orchestrator
          image: us-central1-docker.pkg.dev/techsophy-project/orchestrator-repo/orchestrator:latest
          env:
            - name: PROMETHEUS_URL
              value: "http://prometheus:9090"
          imagePullPolicy: Always
